platform :ios, '9.0'
target 'ModularDemo' do

#提示视图
pod 'MBProgressHUD'

# 网络数据请求
pod 'AFNetworking'

# 轮播图
#pod 'SDCycleScrollView'

# 刷新
#pod 'MJRefresh'

# U-Share SDK UI模块（分享面板，建议添加）
#pod ‘UMengUShare/UI’

# 集成微信(精简版0.2M)
#pod ‘UMengUShare/Social/ReducedWeChat'

# 集成QQ/QZone/TIM(精简版0.5M)
#pod ‘UMengUShare/Social/ReducedQQ'

# 极光推送
#pod 'JPush'

# 微信支付
#pod 'WechatOpenSDK'
end
